/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.hfr.api;

import com.example.hfr.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.annotation.processing.Generated;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-24T16:00:58.522282987+05:30[Asia/Kolkata]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "Facilities", description = "Endpoints related to the health facility registry")
public interface FacilityV2Controller {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /v2/facility/create : Create a new health facility
     *
     * @param facilityCreateRequest Health facility data to add to the registry (required)
     * @return Facility created successfully (status code 201)
     * or Invalid input data (status code 400)
     */
    @Operation(
            operationId = "createFacility",
            summary = "Create a new health facility",
            tags = {"Facilities"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Facility created successfully", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Facility.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid input data")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/v2/facility/create",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<Facility> createFacility(
            @Parameter(name = "FacilityCreateRequest", description = "Health facility data to add to the registry", required = true) @Valid @RequestBody FacilityCreateRequest facilityCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"tenant_id\" : \"state1.phc1\", \"address\" : { \"pincode\" : \"pincode\", \"city\" : \"city\", \"latitude\" : 0.8008281904610115, \"tenantId\" : \"tenantId\", \"addressNumber\" : \"addressNumber\", \"addressLine1\" : \"addressLine1\", \"addressLine2\" : \"addressLine2\", \"detail\" : \"detail\", \"landmark\" : \"landmark\", \"longitude\" : 6.027456183070403, \"addressId\" : \"addressId\" }, \"additionalDetails\" : \"\", \"isActive\" : true, \"facility_name\" : \"Gejjalgetta PHC\", \"facility_details\" : \"\", \"facility_region\" : \"RURAL\", \"facility_category\" : \"facility_category\", \"facility_ownership\" : \"facility_ownership\", \"facility_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"facility_type\" : \"facility_type\", \"wfStatus\" : \"wfStatus\", \"facility_subtype\" : \"facility_subtype\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /v2/facility/assessment/create : Create a new health facility assessment
     *
     * @param facilityAssessmentCreateRequest Health facility assessment data created (required)
     * @return Facility assessment created successfully (status code 201)
     * or Invalid input data (status code 400)
     */
    @Operation(
            operationId = "createHFAssessment",
            summary = "Create a new health facility assessment",
            tags = {"Assessment"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Facility assessment created successfully", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = FacilityAssessment.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid input data")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/v2/facility/assessment/create",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<FacilityAssessment> createHFAssessment(
            @Parameter(name = "FacilityAssessmentCreateRequest", description = "Health facility assessment data created", required = true) @Valid @RequestBody FacilityAssessmentCreateRequest facilityAssessmentCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"tenant_id\" : \"state1.phc1\", \"date_of_assessment\" : \"date_of_assessment\", \"assessed_by\" : \"assessed_by\", \"rowVersion\" : 0, \"final_result\" : \"GO\", \"facility_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"assessment_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"assessment_type\" : \"SOLUTION_DESIGN_TYPE\", \"isActive\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /v2/facility/summary : Get the health facility summary data
     *
     * @param facilityId System generated unique identifier for a PHC (required)
     * @return Concise information about a health facility (status code 200)
     * or Invalid request (status code 400)
     */
    @Operation(
            operationId = "getFacilitiesSummary",
            summary = "Get the health facility summary data",
            tags = {"Facilities"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Concise information about a health facility", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = FacilitySummary.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid request")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/v2/facility/summary",
            produces = {"application/json"}
    )

    default ResponseEntity<FacilitySummary> getFacilitiesSummary(
            @Parameter(name = "facilityId", description = "System generated unique identifier for a PHC", required = true, in = ParameterIn.PATH) @PathVariable("facilityId") UUID facilityId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"summary\" : \"summary\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /v2/facility/search : Search facilities
     *
     * @param tenantId     Filter facilities by tenant (optional)
     * @param facilityId   Filter facilities by id (optional)
     * @param facilityName Filter facilities by name (partial or full match) (optional)
     * @param hfrId        Filter facilities by HFR Id (optional)
     * @param ninId        Filter facilities by NIN id (optional)
     * @return A list of facilities matching search criteria (status code 200)
     * or Invalid query parameters (status code 400)
     */
    @Operation(
            operationId = "searchFacilities",
            summary = "Search facilities",
            tags = {"Facilities"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "A list of facilities matching search criteria", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Facility.class)))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid query parameters")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/v2/facility/search",
            produces = {"application/json"}
    )

    default ResponseEntity<List<Facility>> searchFacilities(
            @Parameter(name = "tenant_id", description = "Filter facilities by tenant", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tenant_id", required = false) String tenantId,
            @Parameter(name = "facility_id", description = "Filter facilities by id", in = ParameterIn.QUERY) @Valid @RequestParam(value = "facility_id", required = false) String facilityId,
            @Parameter(name = "facility_name", description = "Filter facilities by name (partial or full match)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "facility_name", required = false) String facilityName,
            @Parameter(name = "hfr_id", description = "Filter facilities by HFR Id", in = ParameterIn.QUERY) @Valid @RequestParam(value = "hfr_id", required = false) String hfrId,
            @Parameter(name = "nin_id", description = "Filter facilities by NIN id", in = ParameterIn.QUERY) @Valid @RequestParam(value = "nin_id", required = false) String ninId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"tenant_id\" : \"state1.phc1\", \"address\" : { \"pincode\" : \"pincode\", \"city\" : \"city\", \"latitude\" : 0.8008281904610115, \"tenantId\" : \"tenantId\", \"addressNumber\" : \"addressNumber\", \"addressLine1\" : \"addressLine1\", \"addressLine2\" : \"addressLine2\", \"detail\" : \"detail\", \"landmark\" : \"landmark\", \"longitude\" : 6.027456183070403, \"addressId\" : \"addressId\" }, \"additionalDetails\" : \"\", \"isActive\" : true, \"facility_name\" : \"Gejjalgetta PHC\", \"facility_details\" : \"\", \"facility_region\" : \"RURAL\", \"facility_category\" : \"facility_category\", \"facility_ownership\" : \"facility_ownership\", \"facility_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"facility_type\" : \"facility_type\", \"wfStatus\" : \"wfStatus\", \"facility_subtype\" : \"facility_subtype\" }, { \"tenant_id\" : \"state1.phc1\", \"address\" : { \"pincode\" : \"pincode\", \"city\" : \"city\", \"latitude\" : 0.8008281904610115, \"tenantId\" : \"tenantId\", \"addressNumber\" : \"addressNumber\", \"addressLine1\" : \"addressLine1\", \"addressLine2\" : \"addressLine2\", \"detail\" : \"detail\", \"landmark\" : \"landmark\", \"longitude\" : 6.027456183070403, \"addressId\" : \"addressId\" }, \"additionalDetails\" : \"\", \"isActive\" : true, \"facility_name\" : \"Gejjalgetta PHC\", \"facility_details\" : \"\", \"facility_region\" : \"RURAL\", \"facility_category\" : \"facility_category\", \"facility_ownership\" : \"facility_ownership\", \"facility_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"facility_type\" : \"facility_type\", \"wfStatus\" : \"wfStatus\", \"facility_subtype\" : \"facility_subtype\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /v2/facility/update : Update an existing health facility
     *
     * @param facilityUpdateRequest Health facility data with updates (facility_id must be provided in the payload) (required)
     * @return Facility updated successfully (status code 200)
     * or Invalid input data (status code 400)
     * or Facility not found (status code 404)
     */
    @Operation(
            operationId = "updateFacility",
            summary = "Update an existing health facility",
            tags = {"Facilities"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Facility updated successfully", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Facility.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid input data"),
                    @ApiResponse(responseCode = "404", description = "Facility not found")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/v2/facility/update",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<Facility> updateFacility(
            @Parameter(name = "FacilityUpdateRequest", description = "Health facility data with updates (facility_id must be provided in the payload)", required = true) @Valid @RequestBody FacilityUpdateRequest facilityUpdateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"tenant_id\" : \"state1.phc1\", \"address\" : { \"pincode\" : \"pincode\", \"city\" : \"city\", \"latitude\" : 0.8008281904610115, \"tenantId\" : \"tenantId\", \"addressNumber\" : \"addressNumber\", \"addressLine1\" : \"addressLine1\", \"addressLine2\" : \"addressLine2\", \"detail\" : \"detail\", \"landmark\" : \"landmark\", \"longitude\" : 6.027456183070403, \"addressId\" : \"addressId\" }, \"additionalDetails\" : \"\", \"isActive\" : true, \"facility_name\" : \"Gejjalgetta PHC\", \"facility_details\" : \"\", \"facility_region\" : \"RURAL\", \"facility_category\" : \"facility_category\", \"facility_ownership\" : \"facility_ownership\", \"facility_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"facility_type\" : \"facility_type\", \"wfStatus\" : \"wfStatus\", \"facility_subtype\" : \"facility_subtype\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /v2/facility/assessment/_update : Update a health facility assessment
     *
     * @param facilityAssessmentCreateRequest Health facility assessment data updated (required)
     * @return Facility assessment created successfully (status code 201)
     * or Invalid input data (status code 400)
     */
    @Operation(
            operationId = "updateHFAssessment",
            summary = "Update a health facility assessment",
            tags = {"Assessment"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Facility assessment created successfully", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = FacilityAssessment.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid input data")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/v2/facility/assessment/_update",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<FacilityAssessment> updateHFAssessment(
            @Parameter(name = "FacilityAssessmentCreateRequest", description = "Health facility assessment data updated", required = true) @Valid @RequestBody FacilityAssessmentCreateRequest facilityAssessmentCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"tenant_id\" : \"state1.phc1\", \"date_of_assessment\" : \"date_of_assessment\", \"assessed_by\" : \"assessed_by\", \"rowVersion\" : 0, \"final_result\" : \"GO\", \"facility_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"assessment_id\" : \"44e128a5-ac7a-4c9a-be4c-224b6bf81b20\", \"assessment_type\" : \"SOLUTION_DESIGN_TYPE\", \"isActive\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
