export const POPULATE_RESPONSE = "POPULATE_RESPONSE";
export const POPULATE_WORKING_PROJECT = "POPULATE_WORKING_PROJECT";
export const POPULATE_WORKING_FIELD_PLAN = "POPULATE_WORKING_FIELD_PLAN";
export const POPULATE_WORKING_ASSESSMENT_PLAN = "POPULATE_WORKING_ASSESSMENT_PLAN";
export const POPULATE_WORKING_FACILITY = "POPULATE_WORKING_FACILITY";
export const POPULATE_WORKING_AMC_CONFIGURATION = "POPULATE_WORKING_AMC_CONFIGURATION";
export const POPULATE_WORKING_AMC_VISIT = "POPULATE_WORKING_AMC_VISIT";
export const POPULATE_WORKING_FACILITY_DETAILS = "POPULATE_WORKING_FACILITY_DETAILS";