export const LANGUAGE_SELECT = "LANGUAGE_SELECT";
export const FIELD_PLAN_SELECT = "FIELD_PLAN_SELECT";
export const FACILITY_SELECT = "FACILITY_SELECT";
export const SET_REJECTION_REASONS = "SET_REJECTION_REASONS";
export const CLEAR_REJECTION_REASONS = "CLEAR_REJECTION_REASONS";