import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';

import '../blocs/app_init/app_init.dart';
import '../data/app_shared_preferences.dart';
import '../repositories/app_init_Repo.dart';
import '../repositories/assetRepo.dart';

getSelectedLanguage(Initialized state, int index) {
  if (AppSharedPreferences().getSelectedLocale == null) {
    AppSharedPreferences().setSelectedLocale(
        state.appConfig.appConfig!.appConfig![0].languages.last.value);
  }
  final selectedLanguage = AppSharedPreferences().getSelectedLocale;
  final isSelected =
      state.appConfig.appConfig!.appConfig![0].languages[index].value ==
          selectedLanguage;

  return isSelected;
}

class IdGen {
  static const IdGen _instance = IdGen._internal();

  static IdGen get instance => _instance;

  /// Shorthand for [instance]
  static IdGen get i => instance;

  final Uuid uuid;

  const IdGen._internal() : uuid = const Uuid();

  String get identifier => uuid.v1();
}

Future<String> copyFileToLocalDir(File sourceFile) async {
  try {
    // final status = await Permission.storage.status;
    // if (!status.isGranted) {
    //   await Permission.storage.request();
    // }
    final appDocDir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = '${timestamp}_${sourceFile.uri.pathSegments.last}';
    final dest = File('${appDocDir.path}/$fileName');
    final copied = await sourceFile.copy(dest.path);
    return copied.path;
  } on MissingPluginException catch (e) {
    debugPrint('Storage permission check failed: $e');
    return sourceFile.path;
  }
}

/// Given either a local file‑system path or an http(s) URL, returns
/// a [File] pointing at the data (downloaded to temporary dir if needed),
/// or null if neither exists nor could be fetched.
Future<File?> resolveFilePath(String path) async {
  if (path.startsWith('http://') || path.startsWith('https://')) {
    try {
      final resp = await http.get(Uri.parse(path));
      if (resp.statusCode != 200) return null;
      final dir = await getTemporaryDirectory();
      final filename = path.split('/').last;
      final f = File('${dir.path}/$filename');
      await f.writeAsBytes(resp.bodyBytes);
      print("f $f");
      return f;
    } catch (_) {
      print("null here");
      return null;
    }
  } else {
    final f = File(path);
    print("f here $f");
    return await f.exists() ? f : null;
  }
}

String truncateText(String text, {int maxLength = 16}) {
  if (text.length > maxLength) {
    return '${text.substring(0, maxLength)}...';
  }
  return text;
}

String truncateTextFromStart(String text, {int maxLength = 16}) {
  if (text.length <= maxLength) return text;
  final keep = maxLength - 3; // room for “...”
  if (keep <= 0) return '...';
  return '...${text.substring(text.length - keep)}';
}

int parseWarrantyMonths(String s) {
  // Matches patterns like PnY, PnM, or PnYnM
  final regex = RegExp(r'^P(?:(\d+)Y)?(?:(\d+)M)?');
  final match = regex.firstMatch(s);
  if (match != null) {
    final years = int.tryParse(match.group(1) ?? '') ?? 0;
    final months = int.tryParse(match.group(2) ?? '') ?? 0;
    return years * 12 + months;
  }
  // fallback default, e.g., 1 month
  return 1;
}

int parseWarrantyYears(String? s) {
  if (s == null || s.isEmpty || s.length < 1) return 1;
  final regex = RegExp(r'^P(?:(\d+)Y)?(?:(\d+)M)?');
  final match = regex.firstMatch(s);
  if (match != null) {
    final years = int.tryParse(match.group(1) ?? '') ?? 0;
    final months = int.tryParse(match.group(2) ?? '') ?? 0;
    final totalMonths = years * 12 + months;
    return (totalMonths + 11) ~/ 12; // ceiling division
  }
  return 1;
}

enum WORKFLOW_STATUS_FIELD_STAFF {
  ASSIGNED_TO_FIELD_STAFF,
  REJECTED_BY_FIELD_SUPERVISOR,
  REJECTED_BY_QC_SPOC,
  APPROVED_BY_QC_SPOC,
  APPROVED_BY_SUPERVISOR,
  SUBMITTED_BY_FIELD_STAFF,
}

enum WORKFLOW_STATUS_FIELD_SUPERVISOR {
  ASSIGNED_TO_FIELD_SUPERVISOR,
  SUBMITTED_BY_FIELD_STAFF,
  SUBMITTED_BY_SUPERVISOR,
  REJECTED_BY_QC_SPOC,
  APPROVED_BY_QC_SPOC
}

enum WORKFLOW_ACTIONS {
  CREATE_AND_SAVE_DRAFT,
  SUBMIT_REPORT_A,
  SUBMIT_REPORT_B
}

enum REPORT_TYPES {
  NEW_REPORT,
  INBOX,
  SUBMITTED,
  REVIEW,
  REJECTED,
  APPROVED,
  ADD_MORE
}

enum USER_TYPES { SUPERVISOR, FIELD_STAFF }

enum ASSET_TYPES { BATTERY, INVERTER, PANEL }

bool isValidUuid(String value) {
  try {
    // this only checks the format, not whether it was generated by Uuid
    return Uuid.parse(value).isNotEmpty;
  } catch (_) {
    return false;
  }
}

/// A simple in‑memory cache of downloaded files.
final Map<String, File> _fileCache = {};

/// Tries to turn [idOrPath] into a local [File]:
/// 1. If it's already in `_fileCache`, return it.
/// 2. If `isValidUuid(idOrPath)` is true, downloads from
///    `$fileStoreFileUrl$idOrPath` and caches it.
/// 3. Otherwise treats `idOrPath` as a filesystem path and returns the file if it exists.
/// Returns `null` if neither download nor local file exists.
Future<File?> getCachedFile(String idOrPath) async {
  if (_fileCache.containsKey(idOrPath)) return _fileCache[idOrPath];

  // 1) If it's a UUID, try downloading from your file store
  if (isValidUuid(idOrPath)) {
    try {
      final uri = Uri.parse('$fileStoreFileUrl$idOrPath');
      final resp = await http.get(uri);
      if (resp.statusCode == 200) {
        final dir = await getTemporaryDirectory();
        final file = File('${dir.path}/${uri.pathSegments.last}');
        await file.writeAsBytes(resp.bodyBytes);
        _fileCache[idOrPath] = file;
        return file;
      }
    } catch (_) {
      // swallow any network/download errors
    }
  }

  // 2) Otherwise, treat as a local path
  final file = File(idOrPath);
  if (await file.exists()) {
    _fileCache[idOrPath] = file;
    return file;
  }

  // nothing found
  return null;
}

Future<String> getFilestoreUrl(String idOrPath) async {
  String photoId = idOrPath;
  if (!isValidUuid(photoId)) {
    final file = await getCachedFile(idOrPath);
    if (file != null) {
      final repo = AssetRepository();
      photoId = await repo.uploadFile(file);
      print("photoId from api is $photoId");
    }
  }
  print("photoId from return is $photoId");
  return photoId;
}

String fileStoreFileUrl =
    "${envConfig.variables.baseUrl}filestore/v1/files/file?tenantId=${envConfig.variables.tenantId}&fileStoreId=";

class DioErrorParser {
  static Exception parse(DioError dioErr) {
    debugPrint("Dio error: ${dioErr.response?.data ?? dioErr}");

    final serverData = dioErr.response?.data;
    if (serverData is Map<String, dynamic> &&
        serverData.containsKey('Errors')) {
      final errors = serverData['Errors'] as List<dynamic>;
      if (errors.isNotEmpty) {
        final firstErr = errors.first as Map<String, dynamic>;
        final msg = firstErr['message'] as String? ?? dioErr.message;
        return Exception(msg);
      }
    }

    return Exception(dioErr.message);
  }
}
