package facility.web.models;

public enum SolarSolutionDesignType {
    CUSTOM,
    OFF_GRID_DC_SYSTEM,
    NO_DELIVERY_NO_COLDCHAIN,
    DELIVERY_ROOM_ONLY,
    DELIVERY_ROOM_COLDCHAIN,
    COLDCHAIN_ONLY,
    PHC_NO_DELIVERY_NO_COLDCHAIN_LAB,
    PHC_DELIVERY_ROOM,
    PHC_COLDCHAIN_LAB,
    PHC_DELIVERY_COLDCHAIN_LAB,
    PHC_DELIVERY_COLDCHAIN_LAB_DENTAL_ADMIN,
    AC_HYBRID_SYSTEM,
    LIGHT_FAN_EQUIPMENT,
    ONLY_LIGHT_FAN
}