export const LIVELIHOOD_INCIDENT_BUSINESS_SERVICE = "LivelihoodIncident";

export const APPLICATION_STATUS = {
  PENDING_FOR_RESOLUTION: "PENDING_FOR_RESOLUTION",
  OUT_OF_SCOPE_PENDING_POC: "OUT_OF_SCOPE_PENDING_POC",
  OUT_OF_SCOPE_PENDING_VENDOR: "OUT_OF_SCOPE_PENDING_VENDOR",
  OUT_OF_WARRANTY_PENDING_VENDOR: "OUT_OF_WARRANTY_PENDING_VENDOR",
  RESOLVED: "RESOLVED",
  CLOSED_AFTER_RESOLUTION: "CLOSED_AFTER_RESOLUTION",
  CLOSED_AFTER_DECLINE: "CLOSED_AFTER_DECLINE",
} as const;

/** Sentinel stored in InboxRow.sla for an overdue ticket; translated at render time. */
export const SLA_OVERDUE_MARKER = "OVERDUE";

/**
 * Closed/terminal statuses for SLA display purposes — confirmed against SEM's actual
 * im-services workflow config. Deliberately literal (not derived from APPLICATION_STATUS
 * above, which still holds unconfirmed Livelihood-specific status codes) so this doesn't
 * silently inherit that mismatch. APPLICATION_STATUS / RESOLVED_APPLICATION_STATUSES /
 * TERMINAL_APPLICATION_STATUSES / OPEN_DUPLICATE_APPLICATION_STATUSES below are still on
 * the old Livelihood codes and need the same correction before the KPI "resolved" count,
 * isClosedTicket, and duplicate-ticket detection can be trusted against SEM's real data.
 */
export const BLANK_SLA_STATUSES = [
  "RESOLVED",
  "CLOSEDAFTERRESOLUTION",
  "REJECTED",
  "CLOSEDAFTERREJECTION",
] as const;

export const RESOLVED_APPLICATION_STATUSES = [
  APPLICATION_STATUS.RESOLVED,
  APPLICATION_STATUS.CLOSED_AFTER_RESOLUTION,
] as const;

export const TERMINAL_APPLICATION_STATUSES = [
  APPLICATION_STATUS.CLOSED_AFTER_RESOLUTION,
  APPLICATION_STATUS.CLOSED_AFTER_DECLINE,
] as const;

export const OPEN_DUPLICATE_APPLICATION_STATUSES = [
  APPLICATION_STATUS.PENDING_FOR_RESOLUTION,
  APPLICATION_STATUS.OUT_OF_SCOPE_PENDING_POC,
  APPLICATION_STATUS.OUT_OF_SCOPE_PENDING_VENDOR,
  APPLICATION_STATUS.OUT_OF_WARRANTY_PENDING_VENDOR,
  APPLICATION_STATUS.RESOLVED,
].join(",");

/**
 * Maps a pending application status to the single role code allowed to see an
 * unassigned ticket's SLA — confirmed against SEM's actual im-services workflow config.
 */
export const ROLE_STATUS_MAPPING: Record<string, string> = {
  PENDINGFORASSIGNMENT: "COMPLAINT_ASSESSOR",
  PENDINGFORASSIGNMENT_THEFT: "COMPLAINT_ASSESSOR",
  PENDINGFORASSIGNMENT_RMS_DEVICE: "COMPLAINT_ASSESSOR",
  RMS_DEVICE_PENDING_TECH_POC: "COMPLAINT_FACILITATOR_2",
  PENDING_ASSIGNMENT_OUT_OF_WARRANTY: "COMPLAINT_FACILITATOR_1",
  OUT_OF_WARRANTY_PENDING_TECH_POC: "COMPLAINT_FACILITATOR_2",
  OUT_OF_WARRANTY_PENDING_TECH_POC_ROUND_2: "COMPLAINT_FACILITATOR_2",
  OUT_OF_SCOPE: "COMPLAINT_FACILITATOR_1",
  PENDING_ASSIGNMENT_SPARE_PART_NEEDED: "COMPLAINT_FACILITATOR_2",
};
