name: Digit-UI Image Build workflow
on:
  push:
    branches:
      - image-build
#    paths:
#      - 'frontend/micro-ui/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
#    if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # Login to Docker Container Registry
      - name: Login to Docker Container Registry
        run: docker login -u selcofoundation -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Version from Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for digit-ui
        run: |
          docker build  -t selcofoundation/micro-ui:${{ env.VERSION }}-${{ env.commit_hash }} -f  web/docker/Dockerfile .
          docker push selcofoundation/micro-ui:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: frontend/micro-ui
